name: deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    env:
      repository_name: ${{ github.event.repository.name }}

    steps:
      - name: Creating build folder
        working-directory: /var/www/$repository_name.git
        run: mkdir nrjdalal

      # - run: npm i

      # - name: Purging previous push
      #   run: rm -rf /var/www/$repository_name

      # - name: Acivating clean push
      #   run: cp -r /var/www/$repository_name.git/_work/$repository_name/$repository_name /var/www/$repository_name

      # - name: Listing deployed data
      #   run: cd /var/www/$repository_name ; ls -al
